include:
  - proxy.yaml

services:
  web:
    image: cr.yandex/crpmulovogms0f80agjl/webapp:latest
    ports:
      - "80:5000"
    environment:
      - DB_HOST=${DB_HOST}      # FQDN из outputs.tf
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: unless-stopped

